# Site
name: 'Responsible AI Forum <small>@Prague</small>'
name-direct: 'Responsible AI Forum'
description: ''
logo: 'assets/images/logo.png' # TODO make a logo?
favicon: 'assets/images/favicon.ico'
baseurl: ''
# disqus: 'demowebsite'
email: 'responsible-ai@fel.cvut.cz'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
    #  - jekyll-seo-tag

authors:
  rai-team:
    name:       RAI Team
    avatar:     assets/images/logo.png
  martin-krutsky:
    name:       Martin Krutsky
    site:       https://martin-krutsky.github.io/
    avatar:     assets/images/martink.jpg
    bio:        "PhD student of AI at Czech Technical University interested in AI explainability, safety, and ethical use of AI."
    email:      krutsma1@fel.cvut.cz
  #    sal:
  #      name:           Sal
  #      site:           https://www.wowthemes.net
  #      avatar:         /assets/images/avatar1.jpg
  #      bio:            "Hi, I am Sal, the author of Mundana, the theme you're currently previewing. I hope you like it!"
  #      email:          wowthemesnet@gmail.com
  #      twitter:        https://twitter.com/wowthemesnet
  #
  #    jane:
  #      name:           Jane
  #      site:           https://www.wowthemes.net
  #      avatar:         /assets/images/avatar2.jpg
  #      bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
  #      email:          fakemail@gmail.com
  #      twitter:        https://twitter.com/wowthemesnet

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: rai-team
      avatar: assets/images/logo.png

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.md, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules, docker-compose.yml, vendor]
